kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: shopper-db
  name: postgres-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
