apiVersion: v1
kind: ConfigMap
metadata:
  namespace: shopper-db
  name: postgres-config-map
  labels:
    app: postgres
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "123"
